name: pruning
channels:
  - defaults
  - conda-forge
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - alsa-lib=1.2.8
  - anaconda-client=1.11.0
  - anyio=3.6.2
  - aom=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - async-timeout=4.0.2
  - atk-1.0=2.36.0
  - attr=2.5.1
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=6.0.0
  - blosc=1.21.3
  - bokeh=3.0.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.6.1
  - ca-certificates=2023.11.17
  - cairo=1.16.0
  - certifi=2023.11.17
  - cffi=1.15.1
  - cfitsio=4.2.0
  - cftime=1.6.2
  - chardet=5.1.0
  - charls=2.4.1
  - charset-normalizer=2.1.1
  - cloudpickle=2.2.1
  - clyent=1.2.2
  - colorama=0.4.6
  - comm=0.1.2
  - conda-content-trust=0.1.3
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - conda-repo-cli=1.0.27
  - conda-verify=3.1.1
  - contourpy=1.0.7
  - cryptography=39.0.0
  - cudatoolkit=11.6.0
  - curl=7.87.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2023.1.1
  - dav1d=1.0.0
  - dbus=1.13.6
  - debugpy=1.6.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - fftw=3.3.10
  - filelock=3.9.0
  - flit-core=3.8.0
  - fmt=9.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.3.3
  - future=0.18.3
  - gdk-pixbuf=2.42.10
  - gettext=0.21.1
  - ghostscript=10.02.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - glob2=0.7
  - gobject-introspection=1.72.0
  - graphite2=1.3.13
  - graphviz=6.0.2
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.33
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=6.0.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.25.0
  - imagemagick=7.1.0_62
  - importlib-metadata=6.0.0
  - importlib_resources=5.10.2
  - ipykernel=6.20.2
  - ipython=8.9.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jack=1.9.21
  - jbig=2.1
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter-server-proxy=3.2.2
  - jupyter_client=7.4.9
  - jupyter_console=6.4.4
  - jupyter_contrib_core=0.4.0
  - jupyter_contrib_nbextensions=0.7.0
  - jupyter_core=5.1.5
  - jupyter_events=0.6.3
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.6.1
  - jupyter_server=2.1.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=3.5.3
  - jupyterlab-nvdashboard=0.7.0
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.19.0
  - jupyterlab_widgets=3.0.5
  - jupytext=1.14.4
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.0.6
  - libarchive=3.6.2
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=7.87.0
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgd=2.3.3
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libgpuarray=0.7.6
  - libiconv=1.17
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - liblief=0.12.3
  - libllvm15=15.0.7
  - libmamba=1.2.0
  - libmambapy=1.2.0
  - libnetcdf=4.8.1
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.1
  - librsvg=2.54.4
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libsolv=0.7.23
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=252
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzip=1.9.2
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - locket=1.0.0
  - lxml=4.9.2
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown-it-py=2.1.0
  - markupsafe=2.1.2
  - matplotlib=3.6.3
  - matplotlib-base=3.6.3
  - matplotlib-inline=0.1.6
  - mdit-py-plugins=0.3.3
  - mdurl=0.1.0
  - mistune=2.0.4
  - mpg123=1.31.2
  - mpi=1.0
  - mpi4py=3.1.4
  - multidict=6.0.4
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nb_conda_kernels=2.3.1
  - nbclassic=0.4.8
  - nbclient=0.7.2
  - nbconvert=7.2.9
  - nbconvert-core=7.2.9
  - nbconvert-pandoc=7.2.9
  - nbformat=5.7.3
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - netcdf4=1.6.2
  - ninja-base=1.10.2
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.82
  - openjpeg=2.5.0
  - openmpi=4.1.4
  - openssl=3.2.0
  - pandas=1.5.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - pango=1.50.14
  - parallel=20231122
  - parso=0.8.3
  - partd=1.3.0
  - patch=2.7.6
  - patchelf=0.17.2
  - pathlib=1.0.1
  - patsy=0.5.3
  - pcre2=10.40
  - perl=5.32.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=22.3.1
  - pixman=0.40.0
  - pkg-config=0.29.2
  - pkginfo=1.9.6
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.6.2
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.6.0
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.4
  - psycopg2=2.9.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pure_eval=0.2.2
  - py-lief=0.12.3
  - py4j=0.10.9.7
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pycurl=7.45.1
  - pygments=2.14.0
  - pyjwt=2.6.0
  - pynvml=11.4.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.4
  - python-libarchive-c=4.0
  - python_abi=3.9
  - pytz=2022.7.1
  - pywavelets=1.4.1
  - pyzmq=25.0.0
  - qt-main=5.15.6
  - qtpy=2.3.0
  - readline=8.1.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.28.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - ripgrep=13.0.0
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.7
  - scikit-image=0.19.3
  - scikit-learn=1.2.1
  - scipy=1.10.0
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - send2trash=1.8.0
  - setuptools=65.3.0
  - simpervisor=0.4
  - sip=6.7.6
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - stack_data=0.6.2
  - statsmodels=0.13.5
  - terminado=0.17.1
  - threadpoolctl=3.1.0
  - tifffile=2023.1.23.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.8.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - ujson=5.5.0
  - unicodedata2=15.0.0
  - urllib3=1.26.14
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.0
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2022.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - yarl=1.8.2
  - zeromq=4.3.4
  - zfp=1.0.0
  - zipp=3.12.0
  - zlib=1.2.13
  - zlib-ng=2.0.6
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - absl-py==1.4.0
      - accelerate==0.25.0
      - antlr4-python3-runtime==4.9.3
      - arrow==1.2.3
      - astunparse==1.6.3
      - attrs==21.4.0
      - bitarray==2.6.2
      - blessed==1.19.1
      - build==1.0.3
      - cachetools==5.3.0
      - cartopy==0.18.0
      - cirq==1.1.0
      - cirq-aqt==1.1.0
      - cirq-core==1.1.0
      - cirq-google==1.1.0
      - cirq-ionq==1.1.0
      - cirq-pasqal==1.1.0
      - cirq-rigetti==1.1.0
      - cirq-web==1.1.0
      - cleverhans==3.0.1
      - click==7.1.2
      - contextvars==2.4
      - croniter==1.3.8
      - cython==0.29.33
      - d4m==1.2.2
      - dateutils==0.6.12
      - deepdiff==6.2.3
      - deepspeed==0.8.0
      - detectors==0.1.10
      - dill==0.3.6
      - distlib==0.3.6
      - dm-tree==0.1.8
      - dnspython==2.3.0
      - duet==0.2.7
      - email-validator==1.3.1
      - etils==1.0.0
      - exceptiongroup==1.1.0
      - faiss-cpu==1.7.4
      - fastapi==0.88.0
      - ffmpeg==1.4
      - filterpy==1.4.5
      - flatbuffers==23.1.21
      - fqdn==1.5.1
      - fsspec==2023.10.0
      - gast==0.4.0
      - gin-config==0.5.0
      - google-api-core==1.34.0
      - google-api-python-client==2.74.0
      - google-auth==2.16.0
      - google-auth-httplib2==0.1.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - googleapis-common-protos==1.58.0
      - grpcio==1.51.1
      - grpcio-status==1.48.2
      - gviz-api==1.10.0
      - gym==0.23.1
      - gym-notices==0.0.8
      - h11==0.14.0
      - h5py==3.8.0
      - hjson==3.1.0
      - horovod==0.26.1
      - httpcore==0.16.3
      - httplib2==0.21.0
      - httptools==0.5.0
      - httpx==0.23.3
      - huggingface-hub==0.19.4
      - hydra-core==1.3.1
      - hydra-submitit-launcher==1.2.0
      - hydra-zen==0.9.1
      - immutabledict==2.2.3
      - immutables==0.19
      - iniconfig==2.0.0
      - inquirer==3.1.2
      - iso8601==1.1.0
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jax==0.4.2
      - jaxlib==0.4.2
      - jsonpointer==2.3
      - jupyter-tensorboard==0.2.0
      - kaggle==1.5.12
      - keras==2.11.0
      - lark==0.11.3
      - lazy-property==0.0.1
      - libclang==15.0.6.1
      - lightning==1.9.0
      - lightning-cloud==0.5.19
      - lightning-utilities==0.6.0.post0
      - littleutils==0.2.2
      - llsctools==0.0.1
      - llvmlite==0.39.1
      - lz4==4.3.2
      - markdown==3.4.1
      - matlab-kernel==0.17.1
      - matlabengineforpython==R2022a
      - memory-profiler==0.61.0
      - metakernel==0.29.4
      - mmparse==0.6
      - mpmath==1.2.1
      - msgpack==1.0.4
      - mxnet-cu116==1.9.1
      - networkx==2.8.8
      - ninja==1.11.1
      - numba==0.56.4
      - numpy==1.20.3
      - nvidia-dlprof==1.8.0
      - nvidia-nsys-cli==2021.3.2.12
      - nvidia-pyindex==1.0.9
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - octave-kernel==0.35.1
      - ogb==1.3.6
      - omegaconf==2.3.0
      - opacus==1.4.0
      - opencv-contrib-python==4.7.0.68
      - opencv-python==4.7.0.68
      - opencv-python-headless==4.7.0.68
      - opt-einsum==3.3.0
      - ordered-set==4.1.0
      - orjson==3.8.5
      - outdated==0.2.2
      - packaging==22.0
      - pip-tools==7.3.0
      - plotly==5.13.0
      - portalocker==2.7.0
      - promise==2.3
      - proto-plus==1.22.2
      - protobuf==3.19.6
      - py==1.11.0
      - py-cpuinfo==9.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycocotools==2.0.6
      - pydantic==1.10.4
      - pyg-lib==0.1.0+pt113cu116
      - pygraphblas==5.1.8.0
      - pyproject-hooks==1.0.0
      - pyqt5==5.15.4
      - pyqt5-plugins==5.15.4.2.2
      - pyqt5-qt5==5.15.2
      - pyqt5-tools==5.15.4.3.2
      - pyquil==3.3.3
      - pyshp==2.3.1
      - pytest==7.2.1
      - python-dotenv==0.21.1
      - python-editor==1.0.4
      - python-graphviz==0.8.4
      - python-multipart==0.0.5
      - python-rapidjson==1.9
      - python-slugify==8.0.0
      - pytorch-extension==0.2
      - pyyaml==5.4.1
      - qcs-api-client==0.21.3
      - qt5-applications==5.15.2.2.2
      - qt5-tools==5.15.2.1.2
      - ray==2.2.0
      - readchar==4.0.3
      - regex==2022.10.31
      - requests-oauthlib==1.3.1
      - retry==0.9.2
      - retrying==1.3.4
      - rfc3339==6.2
      - rfc3986==1.5.0
      - rich==13.3.1
      - rpcq==3.10.0
      - rsa==4.9
      - sacrebleu==2.3.1
      - safetensors==0.4.0
      - sentencepiece==0.1.97
      - seqeval==1.2.2
      - shapely==2.0.1
      - sortedcontainers==2.4.0
      - ssgetpy==1.0rc2
      - starlette==0.22.0
      - starsessions==1.3.0
      - submitit==1.4.5
      - suitesparse-graphblas==7.4.3.0
      - sympy==1.11.1
      - tabulate==0.9.0
      - tenacity==8.1.0
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-profile==2.11.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.5.1
      - tensorflow==2.11.0
      - tensorflow-addons==0.19.0
      - tensorflow-datasets==4.8.2
      - tensorflow-estimator==2.11.0
      - tensorflow-gan==2.1.0
      - tensorflow-hub==0.12.0
      - tensorflow-io==0.30.0
      - tensorflow-io-gcs-filesystem==0.30.0
      - tensorflow-metadata==1.12.0
      - tensorflow-model-optimization==0.7.3
      - tensorflow-probability==0.19.0
      - tensorflow-text==2.11.0
      - termcolor==2.2.0
      - text-unidecode==1.3
      - tf-models-official==2.11.3
      - tf-slim==1.1.0
      - timm==0.8.19.dev0
      - tokenizers==0.15.0
      - torch==1.13.1+cu116
      - torch-cluster==1.6.0+pt113cu116
      - torch-geometric==2.2.0
      - torch-pruning==1.3.2
      - torch-scatter==2.1.0+pt113cu116
      - torch-sparse==0.6.16+pt113cu116
      - torch-spline-conv==1.2.1+pt113cu116
      - torch-tb-profiler==0.4.1
      - torchaudio==0.13.1+cu116
      - torchmetrics==0.11.0
      - torchtext==0.14.1
      - torchvision==0.14.1+cu116
      - transformers==4.35.2
      - tslearn==0.5.3.2
      - typeguard==2.13.3
      - typer==0.7.0
      - types-python-dateutil==2.8.19.6
      - types-retry==0.9.9.1
      - uri-template==1.2.0
      - uritemplate==4.1.1
      - uvicorn==0.20.0
      - uvloop==0.17.0
      - virtualenv==20.17.1
      - watchfiles==0.18.1
      - webcolors==1.12
      - websockets==10.4
      - werkzeug==2.2.2
      - wilds==2.0.0
      - wrapt==1.14.1
      - wurlitzer==3.0.3
      - xarray==2022.12.0
